// Generated by LiveScript 1.3.1
var fs, path, cli, colors, convert, glob, count, total, files, replace$ = ''.replace;
fs = require('fs');
path = require('path');
cli = require('cli');
colors = require('colors');
convert = require('./convert');
glob = require('glob');
cli = cli.enable('glob');
cli.parse({
  skipRuntime: ['s', 'Don\'t include the `runtime.js` on the HTML files'],
  json: ['j', 'Save the converted SWF files as JSON only.']
});
count = 0;
total = 0;
files = [];
cli.main(function(args, options){
  var i$, to$, results$ = [];
  files = args.map(function(it){
    return {
      path: glob.sync(it)
    };
  });
  total = files.length;
  console.log('');
  for (i$ = 0, to$ = Math.min(files.length, 10); i$ < to$; ++i$) {
    results$.push(convertFile(options));
  }
  return results$;
});
function convertFile(options){
  var file, output;
  file = files.shift();
  output = file.path + '.' + (options.json ? 'json' : 'html');
  return convert(file.path, function(err, obj){
    var ref$, html, json, i$, len$, msg;
    if (err) {
      console.error("Error converting " + file.path + ":");
      console.error(err + '\n');
      return;
    }
    ref$ = obj.output, html = ref$.html, json = ref$.json;
    if (options.skipRuntime) {
      html = replace$.call(html, /<script.+runtime\.js.+<\/script>/, '');
    }
    fs.writeFileSync(output, options.json ? json : html);
    console.log(("[" + (++count) + " of " + total + "] ").green + path.relative(process.cwd(), output));
    if (obj.messages) {
      for (i$ = 0, len$ = (ref$ = obj.messages).length; i$ < len$; ++i$) {
        msg = ref$[i$];
        console.log(("[ " + msg.type + " ] ").yellow + msg.description);
      }
      console.log('');
    }
    if (files.length) {
      return convertFile(options);
    }
  });
}