// Generated by LiveScript 1.3.1
(function(){
  var fs, path, cli, colors, convert, glob, NUM_TRIES, count, total, files, replace$ = ''.replace;
  fs = require('fs');
  path = require('path');
  cli = require('cli');
  colors = require('colors');
  convert = require('./convert');
  glob = require('glob');
  cli = cli.enable('glob');
  cli.parse({
    skipRuntime: ['s', 'Don\'t include the `runtime.js` on the HTML files'],
    json: ['j', 'Save the converted SWF files as JSON only.']
  });
  NUM_TRIES = 3;
  count = 0;
  total = 0;
  files = [];
  cli.main(function(args, options){
    var i$, len$, p, to$, results$ = [];
    for (i$ = 0, len$ = args.length; i$ < len$; ++i$) {
      p = args[i$];
      files = files.concat((fn$()));
    }
    files = files.map(function(it){
      return {
        tries: 0,
        path: path.resolve(it)
      };
    });
    total = files.length;
    console.log('');
    for (i$ = 0, to$ = Math.min(files.length, 10); i$ < to$; ++i$) {
      results$.push(convertFile(options));
    }
    return results$;
    function fn$(){
      switch (false) {
      case !~p.indexOf('*'):
        return glob.sync(p);
      default:
        return p;
      }
    }
  });
  function convertFile(options){
    var file, output;
    file = files.shift();
    output = file.path + '.' + (options.json ? 'json' : 'html');
    file.tries++;
    return convert(file.path, function(err, obj){
      var ref$, html, json, i$, len$, msg;
      if (err) {
        console.error("Error converting " + file.path + "\ on try " + file.tries + "/" + NUM_TRIES + ":");
        console.error(err + '\n');
        if (file.tries < NUM_TRIES) {
          files.push(file);
        }
        return;
      }
      ref$ = obj.output, html = ref$.html, json = ref$.json;
      if (options.skipRuntime) {
        html = replace$.call(html, /<script.+runtime\.js.+<\/script>/, '');
      }
      fs.writeFileSync(output, options.json ? json : html);
      console.log(("[" + (++count) + " of " + total + "] ").green + path.relative(process.cwd(), output));
      if (obj.messages) {
        for (i$ = 0, len$ = (ref$ = obj.messages).length; i$ < len$; ++i$) {
          msg = ref$[i$];
          console.log(("[ " + msg.type + " ] ").yellow + msg.description);
        }
        console.log('');
      }
      if (files.length) {
        return convertFile(options);
      }
    });
  }
}).call(this);
